joaotavora/eglot

eglot-tests.el, eglot.el
This adds buffer formatting capabilities to eglot. I haven't signed the FSF copyright papers yet. I will be improving this PR while waiting for my papers to be processed.
=> Implement formatting

eglot.el
https://github.com/haskell/haskell-ide-engine
=> Add server entry for haskell-ide-engine

eglot.el
I don't have a FSF contributor agreement. But I do think this constitutes as a small contribution.
=> Fix typo with willSaveWaitUntil RPC request

eglot.el
s/didChangeWatchesFiles/didChangeWatchedFiles
=> * eglot.el (eglot-client-capabilities): Fix a typo.

README.md, eglot.el
https://github.com/fwcd/KotlinLanguageServer
=> Add kotlin-language-server

eglot.el
1. `$ pip install python-language-server pyls-mypy`
2. Find a python file with these contents:
```python3
def bar():
"""Test""
pass
```
3. `M-x eglot`
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
make-overlay(nil nil)
#f(compiled-function (diagnostic) "Highlight buffer with info in DIAGNOSTIC." #<bytecode 0xe450d5>)(#s(eglot--diag :buffer #<buffer foo.py> :beg nil :end nil :type :error :text "mypy: EOF while scanning triple-quoted string literal" :backend nil :data-1 ((eglot-lsp-diag :range (:start (:line 2 :character 24) :end (:line 2 :character 25)) :severity 1 :source "mypy" :message "EOF while scanning triple-quoted string literal"))))
apply(#f(compiled-function (diagnostic) "Highlight buffer with info in DIAGNOSTIC." #<bytecode 0xe450d5>) …
```
=> Handle case when diagnostic :character is out of range

README.md, eglot.el
* eglot.el (eglot-server-programs): Add ocaml-language-server.
=> Add entry for ocaml-language-server in eglot-server-programs

README.md, eglot.el
I've been playing around with it a bit and it seems to work pretty well out of the box. R's language server is still pretty young though so a lot of things aren't implemented yet.
=> Add support for R's languageserver

eglot.el
Please check #272 for the details.
=> Fix #272: handle signature label offsets

eglot.el
This is what I alluded to in #309, specifically
https://github.com/joaotavora/eglot/pull/309#issuecomment-537557510,
although it does not achieve all I had in mind.
This is a mere refactoring/cleanup PR.
The 3 commits build on each other to simplify the handling of state
around enabling/disabling `eglot--managed-mode`.  I have been using them
for a few days now.
The individual commit msgs explain the minutiae, I hope.  Overall, the
reasoning is that we have, for good reason, a lot of state in
buffer-local variables, a global hash map (projects to servers) etc.  So
I tried to remove all passing of arguments transporting the same
information (here, the server to use).  At the same time, I put all code
handling the state to where it fits best, IMHO, of course.
=> Simplify mode mechanics, state handling, bookkeeping

Makefile
I think it won't hurt to run these additional tests.  It does not noticeably increases the running time.  The output is slightly longer, but that's acceptable, IHMO.
* Makefile (ELPADEPS): Add company.
=> Make Travis run tests requiring Company

README.md, eglot.el
@joaotavora It should be possible now for you to just click the green button, albeit a different one. When I tried to edit the commit messages the old pull request was automatically closed.
=> Add built-in support for TeX and friends

eglot.el
* eglot.el (Local Variables): Add bug-reference-bug-regexp and
bug-reference-url-format.
=> Support bug-reference-prog-mode

eglot-tests.el
```
* eglot-tests.el (eglot--tests--python-mode-bindings): New. Sets
`python-indent-guess-indent-offset-verbose' to nil.
(auto-detect-running-server)
(auto-shutdown)
(auto-reconnect)
(basic-diagnostics)
(rename-a-symbol)
(basic-completion)
(basic-xref)
(snippet-completions)
(snippet-completions-with-company)
(hover-after-completions)
(python-autopep-formatting)
(python-yaps-formatting)
(eglot-ensure)
(slow-sync-connection-wait)
(slow-sync-connection-intime)
(slow-async-connection)
(slow-sync-timeout): Use `eglot--tests--python-mode-bindings' in these tests.
```
=> Prevent "Cant guess python-indent-offset..." messages in tests.

.travis.yml, Makefile, eglot-tests.el
(See commit message for more information.)
=> Make CI fail if bytecomp emits warning.

eglot.el
This will solve https://github.com/joaotavora/eglot/issues/592
=> Run exit-function only for finished completion

eglot.el
* eglot.el (eglot--lsp-interface-alist): Remove extra Registration entry.
=> eglot--lsp-interface-alist: Remove duplicate entry for Registration

eglot.el
=> (feature): Add :company-kind to eglot-completion-at-point

eglot.el
* eglot.el (eglot--guess-contact): Use eglot--current-project.
(eglot): Adjust docstring.
(eglot-lsp-context): New variable.vc dq
(eglot--current-project): New helper.
(eglot--maybe-activate-editing-mode, eglot--eclipse-jdt-contact):
Use eglot--current-project.
=> Per #687: provide context for finer project-find-functions

eglot.el
=> Fix issues #755, #401; severity not set in textDocument/publishDiagnostics

eglot.el
* eglot.el (eglot--kind-names): update
=> Add missing entries from CompletionItemKind

eglot.el
Not so hardcode, and any advices on `locate-user-emacs-file` will work.
=> Use `locate-user-emacs-file` instead of `concat`

eglot.el
Fixes #476 
* eglot.el (eglot--connect): Print server command to events
buffer.
=> Print server command to events buffer

Makefile
We discussed the possibility of this [elsewhere](https://github.com/joaotavora/eglot/pull/818#issuecomment-1017402876).
=> * Makefile (SELECTOR): Allow passing variable from command line.

NEWS.md, README.md, eglot.el
Hello, I would like to add support for PureScript. Please let me know if there is anything I would need to fix or change.
Best wishes,
alternateved
=> Add language server for PureScript

eglot.el
See https://github.com/joaotavora/eglot/issues/514#issuecomment-1170462637 for explanation
=> Fix #514: Reduce eldoc noise from hover messages

README.md
=> Adding a reference to the useful eglot-x package in the readme
