joaotavora/eglot

README.md, eglot.el
With these two patches I've got `cquery` up and running via `eglot`. Still have a few rough edges to hash out before this is ready to merge:
I have copyright attribution papers on file with the Emacs project. Apologies if I got the commit message format wrong, I had to read up on the style.
=> Introduce cquery support

eglot.el
Currently, by default `markdown-mode` is used to render Markdown-formatted text from the remote language server. This results in confusing renderings when function or variable names contain underscores -- see the below screenshot of help text from the Python language server: 
Using `gfm-mode` instead fixes this:
`gfm-mode` seems to be the recommended way for Emacs buffers to render this style of Markdown [according to the Markdown-mode documentation](https://jblevins.org/projects/markdown-mode/). Since `gfm-mode` is provided by the same package as `markdown-mode`, this shouldn't create any additional dependency issues.
=> Use GitHub Flavored Markdown (GFM) for formatted strings

eglot.el
Here's a very, very small contribution: the solargraph LSP server listed in the list of server programs has a typo, which prevented it from ever launching successfully.
By the way, I'd like to say thank you for your work on this package!
=> Fix typo in the solargraph server program

README.md, eglot.el
* README.md (Supported Protocol Features, Commands and
keybindings): mention workspace/didChangeConfiguration.
* eglot.el (eglot-server-initialized-hook): New hook.
(eglot--connect): Run it.
(eglot-workspace-configuration): New variable.
(eglot-signal-didChangeConfiguration): New command.
=> Close #29: Implement workspace/didChangeConfiguration

eglot.el
See:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32237
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32278
* eglot.el (eglot--apply-text-edits): Inhibit modification hooks and
call them manually for the changed region.
=> Work around Emacs bugs 32237, 32278

eglot.el
* eglot.el (eglot--pos-to-lsp-position): Fix return value when
narrowing is in effect.
=> Close #54: Convert to lsp position correctly when buffer is narrowed

eglot.el
In `eglot--hover-info` we weren't handling the case when MarkedString is a plist. This leads to `wrong-type-argument`, e.g when a class has no documentation and we call `eglot-help-at-point` when using eclipse.jdt.ls.
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
insert(nil)
(save-current-buffer (set-buffer standard-output) (insert blurb))
(progn (save-current-buffer (set-buffer standard-output) (insert blurb)))
(progn (progn (save-current-buffer (set-buffer standard-output) (insert blurb))))
(setq #:value (progn (progn (save-current-buffer (set-buffer standard-output) (insert blurb)))))
(let* ((#:buffer (temp-buffer-window-setup "*eglot help*")) (standard-output #:buffer) #:window #:value) (setq #:value (progn (progn (save-current-buffer (set-buffer …
```
=> Fix wrong-type-argument when MarkedString is a plist

README.md, eglot.el
This PR adds auto-detection for go-mode buffers utilizing https://github.com/sourcegraph/go-langserver.
=> Add go-langserver

eglot.el
* eglot.el (eglot--connect): pass `noquery t` to `make-process`
* eglot.el (eglot--inferior-bootstrap): pass `noquery t` to `make-process`
I'm not sure if you agree with this.
I personally don't like being prompted whether I'm OK with processes I didn't start myself getting killed. Flyspell for example doesn't prompt.
=> When exiting emacs, don't ask the user to confirm killing processes

eglot.el
https://microsoft.github.io/language-server-protocol/specification
> Notification and requests whose methods start with ‘$/’ are messages which are protocol implementation dependent and might not be implementable in all clients or servers. 
> 
> If a server or client receives notifications or requests starting with ‘$/’ it is free to ignore them if they are unknown.
I incline to just not warning in this case as many of such notifications are informative (e.g. status update) or to provide optional features (e.g. `$ccls/publishSemanticHighlighting`). They will not subvert the protocol.
=> Don't warning on $ implementation dependent notifications

eglot.el
Hi,
Since we recommend to use `eglot-ensure` in hook in README:
```lisp
(add-hook 'foo-mode-hook 'eglot-ensure)
```
I think we should add the autoload cookie to it, to avoid the error:
File mode specification error: (void-function eglot-ensure)
=> Add autoload cookie for `eglot-ensure`.

eglot.el
* eglot.el (eglot-ignored-server-capabilites): Add list of possible
choices to :type, along with a user-friendly description.
=> Make eglot-ignored-server-capabilites defcustom more user-friendly

eglot.el
If/when-let are macros that the byte compiler can expand at compile
time. No need to require subr-x at run time.
I've signed the FSF copyright paperwork for Emacs and am OK with that covering this.
=> Require subr-x at compile time

eglot.el
It's a pretty useful feature, however I'm not sure if prepending it like that is the best way to show it.
* eglot.el (eglot-imenu): Prepend :containerName to each symbol, when
provided.
=> Use the container name of a symbol in imenu

eglot.el
Code action literals allow the server to simply return a WorkspaceEdit
for a code action, so the client does not have to execute a command.
* eglot.el (eglot-client-capabilities): Add :codeActionLiteralSupport.
(eglot--code-action-kinds): New variable.
(eglot-code-actions): Apply provided WorkspaceEdit.
=> Add support for code action literals

eglot.el
* eglot.el (eglot-imenu): Use :containerName to build a nested imenu
index alist.
=> Make imenu hierarchical

eglot.el
The `:insertText` field is deprecated, and some servers provide additional features with `:textEdit` and `:additionalTextEdits`. For example, clangd will insert an `#include` for a header which defines some symbol when it's inserted.
* eglot.el (eglot-completion-at-point): Apply the CompletionItem's
:textEdit and :additionalTextEdits when they're present.
=> Add support for TextEdits in completion

eglot.el
* eglot.el (eglot-code-actions): Handle case when the :command field
is not a string.
=> Fix #164: CodeAction command can be a Command object

eglot.el
* eglot.el (eglot-server-programs): add typescript mode to
javascript-typescript-langserver contact
=> Add typescript mode to javascript-typescript-langserver

eglot.el
Hi. Thanks for your cool job.
Function `add-face-text-property` raise errors on every call with nil begin or end parameters.
=> fix errors on add-face-text-property

eglot.el
Fixes two function calls that had the wrong type of arguments resulting in `(wrong-number-of-arguments (1 . 1) 3)` when renaming files in a directory watched by eglot.
=> Fix handle-event calls for 'renamed

eglot.el
* eglot.el (eglot-code-actions): Filter out non-eglot diagnostics
before sending a request to the server.
=> Fix #260: Only consider eglot's own diagnostics in eglot-code-actions

eglot-tests.el, eglot.el
This is an early push to get feedback if I am moving into the right
direction.  Please let me know if this is acceptable.
Basically, I would like some more custom options when/how to display
what part of hover/signature information.  This area already has a
tradition of issues and feature requests, eg, PR #111 and, issue #117
etc.
In my understanding, based on eldoc documentation, eglot is currently
messing with eldoc's internals.  I think that is unneccessary, hence
this PR.
As a result, there's also less global state, and the simpler code has
already helped clear the waters for some more changes that I am
currently trying locally.
=> Clean up eldoc handling to prepare better customizability

eglot.el
* eglot.el (eglot-server-programs): Change the position of the php
language server, otherwise it will always be hidden by the c-mode
server (php-mode is derived from c-mode).
=> Fix invalid guess for php language Server (#288)

eglot.el
This commit prevents watching directories that contain wildcards.
I have run into the following error when using [ccls](https://github.com/MaskRay/ccls), which returns a `extglob **/*` globPattern:
```
Debugger entered--Lisp error: (file-notify-error "Directory does not exist" "/home/juergen/shared/cxx/hello/src/**")
signal(file-notify-error ("Directory does not exist" "/home/juergen/shared/cxx/hello/src/**"))
file-notify-add-watch("**/" (change) (closure ((--cl-handle-event-- . #3) (file-globs ".ccls-cache/" ".ccls-cache/") (globs "**/*") (success) (watchers . [(:globPattern "**/*")]) (--cl-rest-- :watchers [(:globPattern "**/*")]) (id . "didChangeWatchedFiles") (method . workspace/didChangeWatchedFiles) (server . #<eglot-lsp-server eglot-lsp-server>) t) (event) (let* ((x108 (car event)) …
```
=> Expand directory wildcards (#293)

eglot.el
The jsonrpc package (one of eglot's dependencies) recently updated and removed
the line requiring the array package. The `current-line' function is provided by
array and is used by eglot, so let's require array explicitly. Here's jsonrpc's
guilty commit:
https://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/jsonrpc.el?id=c676444a43e4634c1f98ec286b5bd9e46b23216b
=> Require array package to use current-line

README.md, eglot.el
github.com/sourcegraph/go-langserver has been put on the backburner, and
the maintainers themselves advocate using Google's gopls instead.  gopls
is actively developed and, although still labeled "alpha", already works
very nicely.
----
#
=> Change Go LS default to gopls

eglot.el
Some language servers (the PHP one for example) may specify null for
some capabilities in the list of server capabilities. This does not
conform to the specification, but treating it as false is more
reasonable than treating it as true.
=> Treat null/nil server capabilities as false

eglot-tests.el, eglot.el
This got messy, sorry.. rewriting a branch prevents reopening the PR, so here's a new one.
The old discussion is at #305.
=> Option to autoshutdown after killing last buffer

README.md, eglot.el
Closes #302.
* eglot.el (eglot--xref-definitions-method): New variable.
(xref-backend-definitions): Use it.
(eglot-find-declaration, eglot-find-implementation,
eglot-find-typeDefinition): New functions.
=> Support goto-{declaration, implementation, typeDefinition}

README.md, eglot.el
Add support for the Ada Language Server.
Closes #316.
* eglot.el (eglot-server-programs): Add ada-mode entry.
* README.md (Connecting to a server): Add Ada entry.
=> Ada Language Server support

eglot.el
Since we want only the syntax highlight provided by the major mode, it makes sense to ignore user's customization functions on the major mode's hook.
=> Don't run mode hooks in eglot--format-markup

eglot.el
For #328 
There are still two issues about the hover/eldoc:
1. Eglot adds the function name at the beginning, it seems not necessary, at least with Gopls
2. `gfm-view-mode` outputs an empty line at the end
you can reproduce the issue of `gfm-view-mode` with this, it seems if there is a code block at the end of the markdown source, `gfm-view-mode` will add an empty line.
```el
(message
"%s"
(with-temp-buffer
(insert
"Errorf formats according to a format specifier and returns the string as a value that satisfies error\\.\n```go\nfunc fmt.Errorf(format string, a ...interface{}) error\n```\n")
(gfm-view-mode)
(font-lock-ensure)
(buffer-string)))
```
=> Support markdown for hover

eglot.el
This PR allows the user to disable underlining whitespace in the eglot help buffer. I've found that when getting documentation for, e.g., numpy functions, the indentation is always underlined, which is distracting.
This PR disables the underlining of indentation whitespace by setting `nobreak-char-display` to `nil`. The configuration is provided as a customization option.
=> add customization to display/ignore whitespace in help buffer

eglot.el
I'm using Eglot with Gopls. During code completion, `(snippet)` shows all the time, even I'm completing a variable such as `os.O_RDONLY`, I'm not sure it's a bug of Eglot. Anyway it is not useful for me and takes some valuable space, so I want it to be stripped.
=> Remove the display of (snippet) in completion annotation

eglot.el
I'm still not sure whether this issue bothers others as well, but the behavior gets more annoying with non-standard ccls reference methods.  For example, when I request $ccls/navigate and see the result of :textDocument/references.
* eglot.el (eglot--lsp-xref-helper): Display message when no
references have been found instead of calling xref-find-references.
=> Fix #339: fail when eglot-find-* find no references

README.md, eglot.el
* README.md (Connecting to a server): Add metals to the list
* eglot.el (eglot-server-programs): Add metals for scala-mode
=> Add metals as the language server for Scala

README.md, eglot.el
This  PR adds a new defcustom for eglot. When editing using code actions, I want to be able to skip confirmation, since always pressing 'y' gets tedious over time. 
I made sure not to change default behaviour, so this is an opt-in feature.
=> Eglot confirm edit

eglot.el
This PR removes `SKIP-SIGNATURE` from the docstring - the `eglot-eldoc-function` function doesn't take such a parameter
I've signed the FSF agreement.
=> * eglot.el (eglot-eldoc-function): Fix outdated docstring.

eglot.el
This is a first try on the completion-read function. Highly inspired from lsp-mode, maybe this is something we can use?
=> Close #393: eglot-completing-read

eglot.el
This is what the specification requires.  @PerMildner, thanks for
reporting and analyzing the issue.
* eglot.el (eglot-shutdown): Use `notify` instead of `request` for the
`exit` LSP method.
=> Fix #277: Send exit as a notification

README.md
This is something I wanted to write long time ago, but I procrastinated because I'm not good at writing documentation.  Nevertheless, it's a starting point.  Later it can be extended, for example, with the details of the recent #403 
* README.md (animated_gifs): Rearrange and explain the animations.
=> Explain the animations in the README

eglot.el
This just mimics a similar check in `eglot-help-at-point'.
* eglot.el (eglot-eldoc-function): Check emptiness of `contents' more
carefully.
=> Fix #425: Ignore empty hover info

.travis.yml
A previous build (Build #926) failed with:
```
$ curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
$ tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
=> Make curl invocation fail more explicitly in .travis.yml

eglot.el
For example, we have this python file:
```python
def foo(bar):
"""docstring for foo with reserved keywords or
string's opening."""
pass
foo
```
Point is on the last line, `M-x eglot-help-at-point`.
Let's assume this client-server conversation:
```
client-request (id:129) Thu Apr 23 23:05:56 2020:
(:jsonrpc "2.0" :id 129 :method "textDocument/hover" :params
(:textDocument
(:uri "file:///Users/mad/test.py")
:position
(:line 5 :character 3)))
server-reply (id:129) Thu Apr 23 23:05:56 2020:
(:id 129 :jsonrpc "2.0" :result
(:contents
(:kind "plaintext" :value "foo(bar)\n\ndocstring for foo with reserved keywords or\nstring's opening.")
:range nil))
```
`python-mode` is used to handle `value` because `kind` is not `markdown`. As result help buffer looks a little strange.
This PR make eglot use …
=> Use text-mode for plaintext markup

eglot.el
"Match xrefs" are created with `xref-make-match' instead of
`xref-make'.  Match xrefs support `xref-query-replace-in-results' from
the results buffer.
* eglot.el (eglot--xref-make-match): Calculate xref match length from
the eglot range.
=> Create match xrefs when possible.

eglot-tests.el, eglot.el
```
Tests: print contents of *EGLOT ...* buffers in batch mode.
Useful for the CI on github. To be able to see more of the context of
a failure.
* eglot.el (eglot-server-initialized-hook): Changed semantics. Now
called when an instance of `eglot-lsp-server' is created as part of
the "connect to server" flow. Previously, there was no difference
between this hook and `eglot-connect-hook' which continues to be run
once a connection was successfully established. The
`eglot-server-initialized-hook' will now capture ALL server instances
including those that failed to be started. This change was necessary
to make the test suite be able to dump the output of processes that
fail to start when running the test suite in batch mode ("make check"
and the CI.) In PR #448 it was decided that it is ok to …
```
=> Tests: print contents of *EGLOT ...* buffers in batch mode.

eglot-tests.el
```
Enable `python-autopep-formatting` test in Travis
The test actually succeeds. (Unrelated to the previous XDG_CONFIG_HOME
change.)
* eglot-tests.el (python-autopep-formatting): Remove conditional on
environment variable "TRAVIS_TESTING".
Close #441: shield tests from some user customizations
Users' customization of Python indenting style in the standard
XDG_CONFIG_HOME location of ~/.config/pycodestyle could cause spurious
test failures. We prevent this and similar problems by overriding that
environment variable in tests. If this turns out to hurt other
language servers used in the test suite, we'll have to revisit.
* eglot-tests.el (eglot--call-with-fixture): Temporarily set
XDG_CONFIG_HOME to /dev/null.
```
=> Improve reliability of python-autopep-formatting test.

eglot.el
* eglot.el (eglot-events-buffer): Use `eglot-current-server' instead
of `eglot--cached-server' because the latter is declared later in
the file.
=> Close #460: Fix "free variable" warning

eglot.el
Fixes #468.
To reproduce this bug on master:
1. Create some buffer state that causes a flymake error/warning diagnostic to be displayed
2. Disable flymake mode with `M-x flymake-mode`. You will see the flymake overlay annotations disappear.
3. Do some activity in the buffer that triggers eglot diagnostic checking, such as inserting a newline. You will see the flymake overlay annotations reappear. This is a bug: they should only be displayed when flymake mode is active.
=> Don't display flymake annotations when flymake is disabled

README.md, eglot.el
- The erlang language server is at https://github.com/erlang-ls/erlang_ls
I believe this is a trivial change, but I have a copyright assignment for Emacs anyway.
=> Add support for erlang

eglot.el
‘eglot--xref-make-match’ expects a string NAME, but ‘symbol-at-point’ returns a
symbol.
=> Fix type error.

eglot.el
Python file:
```python
int
```
`textDocument/hover` response:
```
(:id 44 :jsonrpc "2.0" :result
(:contents
(:kind "markdown" :value "```python\nint(x: Union[Text, bytes, SupportsInt, _SupportsIndex]=...)\nint(x: Union[Text, bytes, bytearray], base: int)\n```\n\n```\nint([x]) -> integer\nint(x, base=10) -> integer\n\nConvert a number or string to an integer, or return 0 if no arguments\nare given.  If x is a number, return x.__int__().  For floating point\nnumbers, this truncates towards zero.\n\nIf x is not a number or if base is given, then x must be a string,\nbytes, or bytearray instance representing an integer literal in the\ngiven base.  The literal can be preceded by '+' or '-' and be surrounded\nby whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.\nBase 0 means to …
=> Use filter-buffer-substring to get buffer text

eglot.el
* eglot.el (eglot-server-programs): Add required argument for hie-wrapper
Fixes #528
=> Fix: Issue #528 - Add --lsp arg to hie-wrapper for haskell-mode

README.md, eglot.el
Use haskell-language-server instead of deprecated Haskell IDE Engine.
https://github.com/haskell/haskell-language-server
https://github.com/haskell/haskell-ide-engine#deprecated
* README.md: Replace Haskell IDE Engine with haskell-language-server
* eglot.el (eglot-server-programs): Replace hie-wrapper with haskell-language-server-wrapper
=> Use haskell-language-server for `eglot-server-programs`

eglot.el
I decided to go for bold as the default `eglot-highlight-symbol-face`.  I'll outline my thinking here so that possible future objections can be evaluated.
I tried out the chosen face with the built-in themes, and agree with @rvlo (https://github.com/joaotavora/eglot/issues/583#issuecomment-754851909) that bold doesn't give enough emphasis to the highlighted symbols on dark or very busy themes.  On the other hand,
- It's guaranteed not to clash with other colors, an issue reported in https://github.com/joaotavora/eglot/pull/580 for the Doom theme and which I had experienced with Swiper.
- It works well with the default theme, which, by definition, is the only theme that can't redefine the face.
- It's consistent with Eldoc's highlight of the current function argument.
Finally, since the …
=> Close #583: Define a face for symbol highlight

eglot.el
This is needed on Windows.
* eglot.el (eglot--eclipse-jdt-contact): Replace literal ":" by `path-separator'.
=> Use `path-separator' instead of hardcoded colon

NEWS.md, README.md, eglot.el
Make `eglot-code-actions` accept `action-kind` argument.  If there are
only one action of that kind, apply it.
This will allow to create shortcuts for actions of the specific kind.
* eglot.el (aglot--region-bounds): New function.
(eglot-code-actions): Use it; Accept new argument `action-kind`.
Execute the only action of that kind.
(eglot-code-action-inline, eglot-code-action-extract,
eglot-code-action-rewrite, eglot-code-action-quickfix,
eglot-code-action-organize-imports): New commands.
* NEWS.md: New entry.
* README.md (Commands and keybindings): Mention changes to the
`eglot-code-actions` function; Mention new commands.
=> Fix #411 Allow to specify kind of code action to execute

eglot.el
* eglot.el: Require seq.el.
`seq-empty-p' is not autoloaded in Emacs >= 26.3, so it must be
explicitly required.
=> Explicitly require seq.el

README.md
gopls moved to the Go x/tools repository some time ago.
This pull request updates the URL for gopls in the README accordingly.
=> Update gopls URL in README

README.md
`elixir-ls` library has moved to another organization. This PR updates the link to reflect that change.
=> Update README: `elixir-ls` link

eglot.el
phps-mode is available from ELPA, php-mode isn't.  So I think Eglot
should support phps-mode as well.
* eglot.el (eglot-server-programs): Recognize phps-mode as a PHP mode.
=> Support phps-mode

eglot.el
Prior to this, activating gfm-view-mode could echo messages like "markdown-mode math support enabled" to the minibuffer.
See #501
=> Silence messages while formatting markup

eglot.el
* eglot.el (eglot--uri-to-path): make sure that we check whether we have a
nonempty string.  If we do, just return retval as on other operating systems.
=> Fix #610: Handle empty uri on windows

eglot.el
It looks like the important element to zero-length check here is the `proxy` value. It fixes the bug reported in #635, and looks more like what should be done, given what the let-binding does here.
=> Fix #635: Protect against zero-length proxy

eglot.el
* eglot.el (eglot-client-capabilities): Mention
:activeParameterSupport.
Fixup of commit 1f2b0241ca24d78edbd146d17daef6a0e6b2e4f3.
=> eglot-client-capabilities: Indicate support for activeParameter

NEWS.md, README.md, eglot.el
asks all servers managed by eglot to shutdown.
closes #643 ?
about
> for the PR, should we have a function shutting down all servers in the current project, or all servers period? (or both?) 
I went with shutting down all servers since that's more like what the name implies. In my use case both options would be fine, although now that I think of it there seem to be several instances of the same server because different directories of my project are being recognized as different projects (so I'm fixing that with `project.el`)
=> * add eglot-shutdown-all

README.md, eglot.el
No other configuration was needed for formatting or completion on '.'
which was rather surprising. I have not extensively tested zls, though
all immediately expected functionality appears to work well.
=> Add Zig to eglot-server-programs using zigtools/zls

eglot.el
This implements the fix proposed by https://github.com/joaotavora/eglot/issues/525#issuecomment-678540557 to the issue of languages whose major mode has a different name from the language themselves
=> Added the symbol attribute 'eglot-language-id

eglot.el
The repo for ocaml-language-server has been archived and inactive for quite some time:
https://github.com/ocaml-lsp/ocaml-language-server
Meanwhile, ocaml-lsp is the generally-preferred option, and is actively maintained in the ocaml org itself:
https://github.com/ocaml/ocaml-lsp/
=> Switch default langserver for OCaml to ocamllsp

README.md, eglot-tests.el, eglot.el
=> Allow language ID to be overridden via eglot-server-programs

eglot.el
Trivial fix for a recently-added byte compilation warning.
=> Avoid positional args in define-minor-mode to fix warning in Emacs 28

eglot.el
Hopefully the below is enough information to fully-explain this issue. If there's anything else you think I should add (e.g. following the full issue-reporting template, or writing tests), just let me know.
---
I mentioned this in https://github.com/joaotavora/eglot/discussions/675, and now that I've submitted my FSF copyright assignment, I think it's probably safe to just file a PR for the fix. As mentioned in the discussion, there are two issues I came across when attempting to use eglot over TRAMP from MS Windows. This snippet from the event log will help explain the problem:
```
[client-request] (id:1) Thu Apr 22 19:12:57 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
(:processId nil :rootPath "e:/home/jim/test/" :rootUri "file:////home/jim/test" :initializationOptions …
```
=> Fix path/URI usage when using TRAMP from an MS Windows client

eglot.el
Add a property to the eglot-completion-at-point results marking it as non-exclusive. This will allow completion to fall back to other less precise completion backends if eglot returns no results (e.g. dabbrev)
=> Mark eglot completions as non-exclusive

README.md
This fixes a typo in README.md.
The repository is actually called "GNU ELPA", while the protocol itself is called ELPA.
=> Fix "GNU ELPA" typo

README.md
Apparently `eglot` is the recommended `lsp` server for FSharp. See the README at https://github.com/fsharp/emacs-fsharp-mode
=> Mention support for F# in README

README.md
This is just a small addition to the README so that people using TRAMP know that they should update if they're having problems. I also noticed that the `"reporting bugs"` anchor was in the wrong spot, so I moved that to the right place.
=> Per #662, add a note to the README about updating TRAMP to 2.5.0.4+

eglot.el
The Fortran language server `fortls` works well with eglot. I tested both `fortran-mode` for "old" Fortran and `f90-mode`.
=> add automatic detection for Fortran

README.md, eglot.el
@joaotavora [pyright](https://github.com/microsoft/pyright) Language Server Protocol for Python implementation by Microsoft becomes more popular recent days. Good to see it's supported here.
=> Add pyright language server support for python-mode

README.md, eglot.el
Hi, this is a WIP. I wanted to open the pull request in case anyone would like to help out with testing this language server.
`mint ls` was merged into [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/pull/1136) recently.
I thought it would be nice to add it to eglot also :)
Mint's language server is built into the cli interface of [mint](https://github.com/mint-lang/mint/tree/master/src/lsp) [itself](https://github.com/mint-lang/mint/tree/master/src/ls).
Here are the features that are currently supported by the mint language server:
https://github.com/mint-lang/mint/blob/master/src/ls/README.md
Let me know if you would like me to debug anything in particular. 
I'll report back once I fully test all the features that are/are not working.
=> Adds mint language server

README.md, eglot.el
Hello,
trivial patch to add `lua-lsp` for lua-mode.  I've just started to play with lua, but with this plus a `.luacompleterc` file I'm able to get completions for both built-in functions and external modules.
Cheers
edit: I wasn't sure what's the correct order is, so I added lua as last entry.
=> add lua-lsp for lua-mode

README.md, eglot.el
Support Docker files via https://www.npmjs.com/package/dockerfile-language-server-nodejs
Additionally, you need to install the language server:
$ npm install -g dockerfile-language-server-nodejs 
Edit: Additional servers are installed by:
$ npm install dockerfile-bin-language-server-nodejs vscode-css-languageservice-bin vscode-html-languageservice-bin vscode-json-languageservice-bin
=> Add support for Dockerfile, HTML, CSS and JSON

eglot.el
I do not know if this is useful, but it allows me to use docker to run my language servers e,g:
(web-mode . ("/usr/bin/flatpak-spawn" "--host" "docker" "exec" "-i" "dev-image" "typescript-language-server" "--stdio"))
=> Add a variable to withhold the init req process id

README.md, eglot.el
* README.md: Advertise updated executables.
* eglot.el (eglot-server-programs): Prioritize the alternatives.
The {html,css,json}-languageserver executables that are distributed
outside VS Code are not regularly updated by Microsoft; any relevant
updates to the VS Code source tree reach VS Code users without the
need for VS Code developers to go out of their way to publish new
versions of the executables. Consequently, users of other editors who
have been using the server executables from the most obvious NPM
installation are likely using stale versions.
GH hrsh7th, a Vim user, created an NPM package with updated versions
of these executables taken straight from VS Code's source tree. We
therefore prefer to direct users to this other repo, which contains
the appropriate NPM installation …
=> Add up-to-date server executables for HTML/CSS/JSON

eglot.el
@skangas asked me to install this change.  I'd rather send it as a pull request, because I'm not able to end up in a situation with pending requests, therefore I haven't tested this PR.
----
* eglot.el (eglot--mode-line-format): Add tooltip to `pending'.
=> Per #784: Add tooltip describing pending requests

eglot.el
See #769. I guess this information can also be shown via the annotation function. I tested it, and found this way more elegant.
=> Fix #769: support autoImportText from pyright language server

eglot.el
A codeDescription property is, at the time of writing, an object with
an href property (of type URI, or a string), denoting a "URI to open
with more information about the diagnostic error".
It's not obvious how best to put this into a Flymake diagostic
aside from simply appending it to the diagnostic message, so we'll
worry about it some other time.
Fixes #768.
=> Fix #768: Mention lack of support for Diagnostic.codeDescription

eglot-tests.el, eglot.el
https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#diagnosticTag
A DiagnosticTag can be either 1 (DiagnosticTag.Unnecessary) or
2 (DiagnosticTag.Deprecated).  Following the rendering suggestions in
the protocol, we fade out Unnecessary code and strike-through
Deprecated code.
* eglot.el (eglot--lsp-interface-alist): Add Diagnostic.tags.
(eglot-client-capabilities): Advertise supported tags.
(eglot-handle-notification): Assign the appropriate properties.
=> Support optional Diagnostic.tags

Makefile
Avoid the installation of unneeded packages on `make eglot-check`.
=> Use temp directory as package-user-dir for installing ELPADEPS

NEWS.md, README.md, eglot-tests.el, eglot.el
As discussed in #800.
rust-analyzer is the officially blessed Language Server for Rust:
https://github.com/rust-lang/rfcs/pull/2912
Also drop the special support code for RLS.
* eglot.el (eglot-server-programs): Change rust-mode language server
from rls to rust-analyzer.
(eglot-rls, jsonrpc-connection-ready-p)
(eglot-handle-notification): Delete.
* README.md: Update references for RLS to point to rust-analyzer.
=> Change Rust language server to rust-analyzer and drop RLS support

NEWS.md, README.md, eglot-tests.el, eglot.el
This is the second iteration on handling of project wide diagnostics. It should obsolete #640.
This is a simpler variant that simply pushes the diagnostics into flymake. There's also a test that makes sure that we'd get the full expected list of diagnostics.
One caveat: This PR has one undesired behavior, which is the fact that flymake does not set a backend on the diagnostics when reporting them. This means that if you go to a diagnostics listed only by the `flymake-list-only-diagnostics` command, then you'll receive no annotations in the buffer until some edit is made, thus registering `eglot-flymake-backend` I believe a fix in eglot is in order for that, right? Otherwise, it should work ok, I hope
=> Use flymake-list-only-diagnostics - project-wide-diagnostics v2

Makefile, NEWS.md, eglot.el
* eglot.el (eglot--lsp-interface-alist): Add optional CompletionItem.tags.
(eglot-completion-at-point): Add :company-deprecated key and value.
=> Add support for optional CompletionItem.tags

eglot.el
* eglot.el (eglot-completion-at-point): Check the :deprecated property
is `t'.  We do this so that a :deprecated property of :json-false does
not cause a completion candidate to be incorrectly marked as deprecated.
Verified with the Elixir language server with the following file:
``` elixir
IO.puts "Hello world!"
```
=> Properly check the CompletionItem.deprecated property

eglot.el
This was introduced in #482 due to a bad interaction with a specific
server.  But this solution makes hyperlinks in Eldoc buffers
unclickable, because the markdown-mode function that visits a link
relies on the invisible text.
Fixes #865.
* eglot.el (eglot--format-markup): Don't use
'filter-buffer-substring'; instead, keep invisible text.
=> Don't strip invisible text when formatting hover string

eglot.el
A couple of questions:
- Do we need to specify somewhere the Python version required for `jdtls` to run as expected? (See #863)
- This removes plenty of code and I only tested it with a single Java file. Is there any chance someone with bigger projects in his hands can give this a try?
=> Fix #863: Use jdtls for Eclipse JDT

eglot.el
Eglot does support woskspaceEdit/documentChanges, but failed to
advertise this fact.
* eglot.el (eglot-client-capabilities): Set documentChanges to t.
=> Per #853: Change capability 'documentChanges' to t

README.md, eglot.el
There are several issues that report that the Omnisharp server works well together with Eglot, e.g. https://github.com/joaotavora/eglot/issues/241. I have also tested it and it seems to work well. So it would be good if it could be added to the server list.
=> Add C# server Omnisharp to server list

eglot.el
these Emacs variables match to the LSP counterparts.  But this kind of mapping is always debatable.   Nevertheless, I think these make sense.
---
* eglot.el (eglot-format): Map require-final-newline to
insertFinalNewline and delete-trailing-lines to trimFinalNewlines.
=> Map more Emacs variables to fields in FormattingOptions

NEWS.md, eglot-tests.el, eglot.el
* eglot.el (eglot--on-type-formatting-chars): New local var, set
and unset ...
(eglot--managed-mode): ... here based on server's
documentOnTypeFormatting capability, ...
(eglot--post-self-insert-hook): and used here to call eglot-format
for on-type-formatting characters.
(eglot-format): Add new optional argument character to request
:textDocument/onTypeFormatting.
* eglot-tests.el (eglot--simulate-key-event): New helper defun.
(rust-on-type-formatting): New test.
=> Implement on-type-formatting support

NEWS.md, eglot.el
I descended not converting the readme to org-mode and abandoned idea of adding a menu item to the mode-line that opens the local readme.   We can do it later, but it feels unnecessary because the documentation in info format will soon make it obsolete.
----
* eglot.el (eglot--mode-line-format): Capitalize tooltips; add
links to customizations and the readme on github; follow Emacs's
convention of "mouse-2 means help"; establish a convention of
"S-mouse-1 means customize"; move eglot-shutdown to C-mouse-3.
=> Close #792: Rework Eglot's mode-line

README.md
Currently it just links to an image of itself.
=> Fix the the GitHub Actions badge link.

eglot.el
When the completion is exact match, exit-function should still run.
=> Fix exit-function of eglot-completion-at-point

eglot.el
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic
The diagnostics code can be `integer | string`, and the current implementation crashes on `tsserver` because of the integer it returns. This is a small fix to deal with that.
=> Use format string instead of concat

eglot.el
As per #776
* eglot.el (eglot-events-buffer-size): Mention that you need to
restart the connection for 'eglot-events-buffer-size' to take effect.
=> Update docstring of eglot-events-buffer-size 

eglot.el
* `eglot.el` (`eglot--{}`): Specify smallest hash table `:size`, to spare ~1KiB according to `memory-report-object-size` (#315).
=> Reduce memory footprint of eglot--{}

NEWS.md, README.md, eglot.el
Hi,
This adds support for [jedi-language-server](https://github.com/pappasam/jedi-language-server) so when I run `eglot` in the with `M-x` it will be detected and listed as one of the language server options. 
I found `jedi-language-server` to be quite performant and a nice experience with `eglot`.
`eglot` configuration is mentioned in the `jedi-language-server` `README`:
https://github.com/pappasam/jedi-language-server#emacs
=> Add support for jedi-language-server

README.md
The original author has stopped developing fortls and a new fork from the author of the vs code fortran extension (https://github.com/fortran-lang/vscode-fortran-support) has taken over.
=> update link for fortls

NEWS.md, README.md, eglot.el
This adds support for the Perl::LanguageServer module which implements an LSP server for the Perl language.
I'll rebase the commit as soon as I have the PullRequest number to make the NEWS.md entry.
I have done the FSF copyright paperwork some years ago, I have contributed to official Emacs:
https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/org/ob-vala.el?h=emacs-27#n5 (`ob-vala.el` has since been moved to org-contrib, so it's not part of Org 9.5 or Emacs 28 any more as I have just found out).
Is this enough proof to skip the "copyright exemption" tag?
The available server features are:
```
[server-reply] (id:1) Thu May 12 22:05:45 2022:
(:id 1 :jsonrpc "2.0" :result
(:capabilities
(:documentRangeFormattingProvider t :workspaceSymbolProvider t :workspace
(:workspaceFolders
(:supported …
```
=> Add out-of-box support for Perl LSP server

NEWS.md, README.md, eglot.el
Marksman is an LSP server for Markdown: https://github.com/artempyanykh/marksman
It supports a bunch of LSP features such as symbols, references, rename, diagnostics, etc. and already has integrations with a number of LSP clients.
_Context_: I'm the author of Marksman and recently started using it with Eglot. I figured it would be nice to have an out-of-the-box support.
=> Add Markdown LSP via Marksman

eglot.el
This change could eventually be removed when https://github.com/eclipse/eclipse.jdt.ls/pull/2207 gets merged.
=> Per #1008: Fix jdtls support

eglot.el
* eglot.el (eglot--apply-workspace-edit): When both documentChanges
and changes are present, prefer the documentChanges.  By doint that we
ensure that we don't double edit, rendering the document in an
unusable state.
=> Fix #704: Prefer documentChanges over changes
